### ISSUE TITLE
Sequence being multiplied by float when decoding opus audio

### ISSUE THREAD

**Issue by Cottonwoods** [azlux/pymumble#1]
Hey, I emailed you about this yesterday.

The problem occurs when trying to decode opus audio from a mumble stream with [mumblerecbot](https://github.com/bmwiedemann/mumblerecbot). I tried using @Robert904's original and was hoping @bmwiedemann's fork would work, but ran into the same issue.

The error given is:
`2016-06-30 14:03:41,946-PyMumble-ERROR-error while decoding audio. sequence:0, type:4. can't multiply sequence by non-int of type 'float'`
This error is thrown when trying to convert opus audio to pcm on line 48 in pymumble/soundqueue.py:
`pcm = self.decoders[type].decode(audio, PYMUMBLE_AUDIO_PER_PACKET)`
The error is thrown to a higher level in mumble.py:
`AttributeError: 'NoneType' object has no attribute 'duration'`
This is due to the sound failing to be added to a user's queue.

To reiterate: when trying to record audio from a mumble stream pymumble fails to decode the opus packet and return pcm. I can't be sure if this is a problem with pymumble or opuslib. I'm using @OnBeep's version 1.1.0 of [opuslib](https://github.com/OnBeep/opuslib) on Python 2.7.11. Any help or advice on the matter would be appreciated.

Thanks,
Cottonwoods

**Comment by azlux** [comment]
can you give me the line of pymumble where this error come from.

**Comment by Cottonwoods** [comment]
line 439 in pymumble/mumble.py
in the callback function 'sound_received' calls a function 'add' in
line 48 in pymumble/soundqueue.py
which throws the error

**Comment by azlux** [comment]
The decode function need the frame size. Are you sure the audio is not None ? 
Run pymumble into the debug mode, you will see input and output from mumble.

**Comment by Cottonwoods** [comment]
Using a debug message in add:
`self.mumble_object.Log.debug("Audio: {a}".format(a=audio))`
Gives the output:
`2016-06-30 16:20:01,251-PyMumble-DEBUG-Audio: x�!�)   �b�P�d
                                                              �   �Ŗ   �9'�B� ۚQ���p���a��������-A���Hy��*���4� ���6�������Q�~�!��L�`
Which is the audio packet binary expressed in the terminal

Decode uses the constant `PYMUMBLE_AUDIO_PER_PACKET` defined as `float(20)/1000` in pymumble/constants.py

**Comment by Cottonwoods** [comment]
Of note is the audio frame in debug mode:
`2016-06-30 16:23:22,388-PyMumble-DEBUG-Audio frame : time:1467321802.388569, last:True, size:100, type:4, target:0, pos:4`
According to comments last should always be False when decoding Opus frame data:
`# should actually always be 0 as OPUS can use variable length audio frames`

**Comment by azlux** [comment]
Do you want to give me your code ? i will try to reproduce this problem ! (On mail is you don't want it plublic)
Or it is the mumblerecbot without modification ?

**Comment by Cottonwoods** [comment]
Yes, mumblerecbot without modification. Just cloned [mumblerecbot](https://github.com/bmwiedemann/mumblerecbot) and ran `make` in mumblerecbotfast with `PLATFORM = UNIX` on Arch. I copied pymumble to the root directory of mumblerecbot since the version installed by pip is old. It starts fine, but crashes whenever someone speaks in the same channel as it resides.

Thanks

**Comment by azlux** [comment]
ok, i have reproduce your issue

**Comment by Cottonwoods** [comment]
Très bien! I'm not terribly familiar with the mumble packet structure, but it's possible it may have changed in new versions while the pymumble library lagged behind (at least the sound_received hook)

**Comment by azlux** [comment]
ok, i have a old implementation from a friend who work fine. I will try to find the issue

**Comment by azlux** [comment]
So much time for only one line.. Rhaaaa !!!

**Comment by Cottonwoods** [comment]
So it was using the wrong constant?

**Comment by azlux** [comment]
Yes, opuslib has change since the first version and now need the number of frames, but the constant was the time of a frame.
Do it work now ?

**Comment by Cottonwoods** [comment]
Yes, perfect. Good work!
