### ISSUE TITLE
Update pypi to latest version.

### ISSUE THREAD

**Issue by Alex-Programs** [azlux/pymumble#100]
First, thanks for writing the ACL. Second, currently the pypi is out of date (on 1.5) - just letting you know.

**Comment by azlux** [comment]
Hi, It's not out of date, it's just because I didn't release any new version.
Features was in testing.
Since no bug have been reported, I will make v1.6

**Comment by azlux** [comment]
Done https://github.com/azlux/pymumble/commit/9ce86376043ba71c519010abb07fb75ea6c3843c !

**Comment by Alex-Programs** [comment]
Thanks.
