### ISSUE TITLE
Issues with the reliability of adding to and removing from groups.

### ISSUE THREAD

**Issue by Alex-Programs** [azlux/pymumble#101]
Reproduction 1:
```python
import pymumble_py3
import asyncio
import shared

class MumbleInstance():
    def __init__(self, ip, nick):
        self.ip = ip
        self.nick = nick
        self.loop = asyncio.get_event_loop()

    async def start(self):
        self.instance = pymumble_py3.Mumble(self.ip, self.nick, reconnect=True, certfile="cert.pem", keyfile="key.pem")

        self.instance.start()

        self.instance.is_ready()

        self.instance.users.myself.register()

        self.instance.my_channel().send_text_message("Bridge bot initialised and connected.")

        print(str(self.instance.users))

        self.removeFromGroup("tempgroup", 45)

        while True:
            print("Done")
            await asyncio.sleep(1)

    def addToGroup(self, groupName, mumbleID):
        root = self.instance.channels[0]
        root.get_acl()

        root.acl.add_user(groupName, mumbleID)

    def removeFromGroup(self, groupName, mumbleID):
        root = self.instance.channels[0]
        root.get_acl()

        root.acl.del_user(groupName, mumbleID)

inst = MumbleInstance(Redacted, "BridgeBot9000")

asyncio.get_event_loop().create_task(inst.start())

asyncio.get_event_loop().run_forever()
```

Expected result:
User (UID 45, already in group "tempgroup") is removed from "tempgroup".

Actual result:
User is not removed from the group. No exceptions occur.

The same issues occur when trying to add to groups. Sometimes it is fixed with a bot restart, sometimes not, and often it will work for a while then after some more testing, fail. I'm sorry that I can't get more concrete data - it's simply been failing in every way for the last 20 minutes of trying to test, which makes it quite hard to narrow it down. In general the ACL feature is unreliable.

Despite this, thank you for making it, and I do not mean to say you are a bad programmer - I would have no idea where to start with implementing this. Thank you for making PyMumble, and for being so responsive.

**Comment by azlux** [comment]
Ok, I can see the issue.
There are no check if an ID is already in the group, so adding multiple time make it hard to delete because it's appear more than one.
![image](https://user-images.githubusercontent.com/11210117/115129117-4b05dc80-9fe3-11eb-8600-748a01184fbb.png)

I need to make ID in group unique.

**Comment by azlux** [comment]
Can you check now ?

**Comment by Alex-Programs** [comment]
Thanks, I'll check tonight.

**Comment by Alex-Programs** [comment]
@azlux Just tested it, same issue. I'm definitely running the latest version. (Checked the code)

**Comment by azlux** [comment]
Ho, I see, 
First step :
`root.get_acl()` is a async function to ask channel information.
When the function return, that doesn't mean that you already have the information.

Put some sleep after the `get_acl`, that should work. Or you can just remove it, the function `del_user`will call [automatically call](https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/acl.py#L53) `get_acl` if the acl isn't populate. This part isn't asynchronous ([See this code](https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/acl.py#L38-L44))

Second step:
I'm search what can I do to improve the ACL functions.

Here is my test code:
```python3
mumble = pymumble_py3.Mumble(server, nick, password=pwd, debug=False, certfile="xana.pem", keyfile="xana.pem")
mumble.start()
mumble.is_ready()

time.sleep(1)
mumble.channels[0].get_acl()
time.sleep(1) # Fail if this line is removed

print(mumble.channels[0].acl.groups['test'].add)
mumble.channels[0].acl.add_user(group_name='test', user_id=77)
print('Azlux added to test')
print(mumble.channels[0].acl.groups['test'].add)
```

**Comment by Alex-Programs** [comment]
Thanks, I'll do that.

**Comment by Alex-Programs** [comment]
Seems to be working now! Thanks for all the help, you've been great.

**Comment by Alex-Programs** [comment]
@azlux This can probably be closed now.

**Comment by azlux** [comment]
Better API.md, and better function name. Be carefull, `get_acl()` have been rename to `request_acl()`

**Comment by Alex-Programs** [comment]
Could you update it on the python package index?

**Comment by azlux** [comment]
Added to the small release https://github.com/azlux/pymumble/releases/tag/1.6.1
