### ISSUE TITLE
Fetch server info without connecting

### ISSUE THREAD

**Issue by xPMo** [azlux/pymumble#103]
I'm not experienced with Mumble's protocol, but given that the Mumble client shows the current number of users connected when selecting a server, I believe this should be possible. (I would like to write a script which simply queries the server to see how many users are connected.)

If it's not feasible, not in-scope, or you just don't have time to work on it yourself, do you know of any docs (or an existing script that I wasn't able to find) that would help me do this? Thanks.

**Comment by azlux** [comment]
It's not part of protobuff mumble protocol. There are a separate "ping" function to do that. I've never thing about adding it to pymumble.
You can find an example here : https://gist.github.com/azlux/315c924af4800ffbc2c91db3ab8a59bc

**Comment by xPMo** [comment]
Thanks, that's exactly what I was looking for. ([using it for a matrix bot](https://github.com/xPMo/hemppa-bot/blob/master/modules/mumble.py))
