### ISSUE TITLE
Combine multiuser sounds

### ISSUE THREAD

**Issue by ajmandourah** [azlux/pymumble#106]
Hello,
I am trying to create a bridge between mumble and another platform and I am struggling when getting the audio from multiple users.
When one user talks the output stream is great. But as soon as multiple users talks in the same time stuttering and delay occurs.
I am basicly looping through users and checking if there is sound in the sound queue. Then if only one sound item per loop detected I yield that otherwise I combine the sounds to gather and yield the results.
I tried using different libraries like pydub's overlay, audioop but the same result occur. Any tips on combining the sounds to one file /stream of bytes?

**Comment by azlux** [comment]
Can you try with the callback ? 
Ex : https://github.com/azlux/pymumble/blob/pymumble_py3/examples/echobot.py
The callback is asnyc, this should avoid the time you manage the sound, and freeze the audio from other people.

**Comment by ajmandourah** [comment]
I have tried it with the callback. I am now directly yielding the received sound chunk to flask response. If one speaker talks its fine, as soon as 2 talks in the same time stuttering occur. The server is hosted on the same network so no issue here and my cpu is capable enough.

If you would merge the sound all to gather and send it like a single stream of data what would you use?
Audioop and pydub gave me the same issue. And I don't know if it's python's slowness is at fault.

I tried looking at mumblerecbot  implementation but it seems it is saving separate audios alltogather.

**Comment by azlux** [comment]
Hi,
I saw the first bot made by Robert merge audio https://github.com/Robert904/mumblerecbot/blob/master/mumblerecbot.py#L213-L248

To be honest, I've never tried it.

If you save the audio in 2 differents files, to you heard the stuttering ?

**Comment by ajmandourah** [comment]
i will give it a try ... meanwhile have a look at my code if anything you would think is wrong. here I tried to play with threading (thought its a bottleneck there) https://pastebin.pl/view/caee7795

I actually suspect its a performance related to python lists as I append every sound to it but then I tried it with directly yielding from the callback function I get the same reaults

**Comment by azlux** [comment]
Maybe this repo can help you ? https://github.com/c3lingo/c3lingo-mumble
I see some audio implementations

**Comment by azlux** [comment]
ok, I'm able to reproduce your current issue.
I'll work on it.

**Comment by azlux** [comment]
I'm not able to finish the save-to-wav part (need to stop today)
But I'm able to heard both users sound in the same time.
https://bin.azlux.fr/?c2affff814611b17#6GmhmEmJ4WfQtLctB7uaVNKBpanwCBoQQv3JtYAoU5Ae

The main issue here is you try to append all PCM audio frame. But when 2 frame come in a same time, you need to save them separately and merge them later.

**Comment by ajmandourah** [comment]
Thanks for your time.

with Pyaudio there is no issue producing the sound through the speaker, this is kinda similar to the audio only client example. one think though , and I have it wrong earlier though as I misunderstand pyaudio, "Writing" to the stream means directly through the output. "reading" get it from your input (your mic here) and has nothing to do with mumble if you are not intending to broadcast it to the server. this means unless you are doing a loopback device there is no way to save your output stream.

The issue is when saving directly after you collect the soundchunks from the callback. As you have mentioned above :

```
The main issue here is you try to append all PCM audio frame. But when 2 frame come in a same time, you need to save them separately and merge them later.
```

I tried earlier to merge the chunks using pydub overlay method. but the same thing happend.

in the link you provided https://github.com/c3lingo/c3lingo-mumble rather than list the dev is using arrays which should be fater ti iterate.. I will try this also and see what happen.
Also I noticed that he is not merging the chunks

**Comment by ajmandourah** [comment]
Just a little update! I now successfully managed to get a working multiuser sound using C3lingos scripts with little modification for the bridge. I have never worked with arrays before and audio is a complicated subject. 

Simply the mixing is happening by adding the 2 int together then converting them to bytes before streaming/yielding(in my case).

here is a sample:

```
    ts = time.time() - INTERVAL
    while True:
        start = time.time()
        buffer = array('h',[0]*int(INTERVAL*RATE))
        for session in mumble.users.keys():
            sample = array('h')
            user = mumble.users[session]
            while len(sample) < len(buffer):
                sound = user.sound.get_sound(INTERVAL)
                if not sound:
                    break
                sample.frombytes(sound.pcm)
            if sys.byteorder == 'big':
                sample.byteswap()
            for i in range(0, len(sample)):
                buffer[i] = clip(buffer[i] + sample[i])
        if sys.byteorder == 'big':
            buffer.byteswap()
        yield buffer.tobytes()
        wait = INTERVAL * 1 - (time.time() - start)
        if wait > 0:
            time.sleep(wait)
```
What I have failed to understand though the "wait" part at the end, if you can shine a light upon it? I already asked the dev for it also. without that part it will cause a long pauses.

The full code is here. 
https://pastebin.pl/view/398a9d8e
My idea is to make a bridge to other platforms. I now working on Telegram and I have made a mini client bot which have a connection to botamosique. This now will allow a stream of mumble audio which can be then connected to other platforms.

Thanks for your help

**Comment by azlux** [comment]
Do you need more help on this issue ?

**Comment by ajmandourah** [comment]
one Question only... anyway to compress the audio through pymumble. the size is large for streaming.

**Comment by azlux** [comment]
For incoming audio, no.
For outgoing audio, there are two points you can modify:
- changing the opuslib profile : https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/mumble.py#L553 in voip in case you have voice only.
- changing the bandwidth https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/mumble.py#L462  in bps, the default is quite high for quality purpose. https://wiki.mumble.info/wiki/Murmur.ini#bandwidth

**Comment by ajmandourah** [comment]
so for incoming the omly way is to ue ffmpeg to stdout and such

this created a delay for... I guess this is the limit here,

**Comment by azlux** [comment]
Do you still need help on this ticket ?
