### ISSUE TITLE
Support for channel listener

### ISSUE THREAD

**Issue by Natenom** [azlux/pymumble#109]
To be able to implement https://github.com/azlux/botamusique/issues/283 :)

**Comment by azlux** [comment]
This request is part of mumble 1.4.
There are a protocol change, see : https://github.com/mumble-voip/mumble/blob/8c99fe8119ce00fbcba55c69bde0a48383e7fa79/src/Mumble.proto#L222-L225
Look not hard to implement on pymumble side. I will take a look.

**Comment by azlux** [comment]
fix since a long time into https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/users.py#L269-L283 with #120
