### ISSUE TITLE
Connection error w/ known good Murmur server.

### ISSUE THREAD

**Issue by Piper984** [azlux/pymumble#110]
I have installed Pymumble on a Raspberry Pi Zero with the following commands:
On a current Rasperry Pi OS (5.10.35+ Kernel)
```
1) sudo apt-get install libopus-dev
2) sudo pip3 install pymumble
```

I pulled down the examples from git.  Using the echoboy.py example, I pointed to a local murmur server that I have iOS + Desktop mumble clients connected to and working fine.

When the mumble.stat() function is called, I receive the following error:
```
2021-05-29 17:05:03,526-PyMumble-DEBUG-Working in MONO mode.
2021-05-29 17:05:03,579-PyMumble-DEBUG-connecting to 192.168.42.3 (SocketKind.SOCK_STREAM) on port 64738.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/pymumble_py3/mumble.py", line 128, in run
    raise ConnectionRejectedError("Connection error with the Mumble (murmur) Server")
pymumble_py3.errors.ConnectionRejectedError: 'Connection error with the Mumble (murmur) Server'
```

I tried setting debug=True to see if there was any more data but no other messages.   It would be great to know how to better troubleshoot my issue, so if you have any recommendations please advise!  Thx for any help!

**Comment by Piper984** [comment]
FYI: I did think to look at the murmur log file and see this when I attempted to connect from the pymumble script:
```
<W>2021-05-29 17:32:35.766 1 => <38:(-1)> New connection: 192.168.42.155:35450
<W>2021-05-29 17:32:35.783 1 => <38:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number [13]
```

I double checked and systems times are all correct.  Is there a something I could look at regarding the encryption scheme ?

**Comment by azlux** [comment]
Hi,
Do you have the murmurd version ? Look like you have an old one.

**Comment by Piper984** [comment]
Hi Azlux: I just looked it up:
```
murmurd --version
<F>2021-05-29 18:36:25.119 murmurd -- 1.2.12-1ubuntu1
```

**Comment by azlux** [comment]
That the issue murmur 1.2.x have very old ssl.
Can you update to murmur 1.3.x ? 

Correction : should be the system how have old ssl. Can you upgrade your ubuntu too ?

**Comment by Piper984** [comment]
Yes, I'll try that tomorrow and reply back with what I learn.  Thx!  -Chris

**Comment by Piper984** [comment]
Hi Azlux,

Thanks for the guidance on trying newer release of murmur.  This morning I installed Ubuntu 21.04 on a dev box, installed mumble-server from the repository, and Pymumble script connected to the server!  

Would it be possible to just pull and compile the latest murmur code on Ubuntu 16.04?  Or are there loads of SSL and other system dependancies that make it not really worth doing?

Thanks again!  My next task is to loop audio In and Out from USB Audio device, so if there are any reference scripts online showing... a link would be appreciated!

**Comment by azlux** [comment]
Using last version on Ubuntu 16 need to compile the code yourself, or use backport repository.

I will now close this ticket.
