### ISSUE TITLE
User count and ping

### ISSUE THREAD

**Issue by pramadhana92** [azlux/pymumble#114]
Hi,

Can we get user count and ping result using pymumble like we get in mumble client in desktop?

![image](https://user-images.githubusercontent.com/44948853/127021704-bf00c795-7e26-4cfa-b449-608ac453dbf4.png)

Thanks!

**Comment by azlux** [comment]
Duplicate of https://github.com/azlux/pymumble/issues/103
Please check this issue.

**Comment by pramadhana92** [comment]
thanks a lot for your answer!
