### ISSUE TITLE
pymumble unable to connect to FiveM embedded Mumble server

### ISSUE THREAD

**Issue by Dalrae1** [azlux/pymumble#119]
Upon connecting to my FiveM embedded Mumble server, it completely fails to connect. No error messages were provided except for "Connection error with the Mumble (murmur) Server"
Connecting with the official Mumble client works fine

**Comment by azlux** [comment]
Do you know your mumble server version ?

**Comment by Dalrae1** [comment]
> Do you know your mumble server version ?

I think it uses a slightly modified version 1.3.4

**Comment by Dalrae1** [comment]
> Do you know your mumble server version ?

I can provide you with a currently functioning (empty) FiveM Mumble server, as well as a FiveM Mumble server with 300+ people connected concurrently.

**Comment by Dalrae1** [comment]
After some more testing, I have concluded that I'm fucking dumb and pymumble does connect correctly.

**Comment by azlux** [comment]
No problem.
I'm happy you find out the solution.
