### ISSUE TITLE
[opuslib] DeprecationWarning: tostring() is deprecated. Use tobytes() instead.

### ISSUE THREAD

**Issue by Lartza** [azlux/pymumble#12]
opuslib is finally starting to show it's age.
I forked opuslib and fixed a couple of things https://github.com/Lartza/opuslib
Not sure how you want to handle this, I am not 100% sure if tobytes is compatible with Python 2 I pretty much deal with 3 only but tostring might be deprecated in 2.7 too.

FWIW DeprecationWarning caused a huge amount of spam to terminal when playing sound, fixed simply with https://github.com/Lartza/opuslib/commit/1a6b7097d01f667d06a12feeb61e13eb0869d711

The set -> set_ctl refactor commit is untested but I don't see why it wouldn't work, it's not used outside ctl.py afaict

**Comment by azlux** [comment]
I don't take care of Python 2 anymore, Pymumble is now Python3 :P  
I think the best thing to do is to Pull request your changes on the opuslib main repo to have the new version available with pip3.

**Comment by Lartza** [comment]
Here's hoping :) https://github.com/OnBeep/opuslib/pull/3

**Comment by azlux** [comment]
It's good to have hopes. It's merged. https://github.com/OnBeep/opuslib/commit/efcedda306cd7acea42585738ca9ea16b980e202 opuslib 2.0.0 is available on [Pypi](https://pypi.python.org/pypi/opuslib/2.0.0)
There are multiple changed, I need to check if everything is working ? @Lartza have you test it ?

**Comment by Lartza** [comment]
The changes are kind of minor overall. Just tested it with my bot and everything seems to work fine.
