### ISSUE TITLE
Getting the current channel

### ISSUE THREAD

**Issue by robozman** [azlux/pymumble#17]
Is there a simple way that I'm missing to get the channel object of the channel the current Mumble object resides in?
Thanks

**Comment by robozman** [comment]
Figured it out. I'll leave this here for anyone else who is puzzled. 
Mumble.channels[Mumble.users.myself["channel_id"]]

**Comment by robozman** [comment]
Figured it out. I'll leave this here for anyone else who is puzzled.
Mumble.channels[Mumble.users.myself["channel_id"]]

**Comment by azlux** [comment]
👍 
Good work.
The documentation still a little bit messy. I think a rewrite would be necessary.

**Comment by robozman** [comment]
I'm currently working on a project making use of pymumble, so once I've wrapped my head around the API I'll see if I can share some of that understanding back.

**Comment by azlux** [comment]
Poke me or come on my mumble if you need help again for the implementation !

**Comment by WhatsCS** [comment]
I must be missing something, I'm currently using the pymumble_py3 branch and `Mumble.users.myself` does not have an entry for `channel_id`, only `name` and `session` exist.

**Comment by azlux** [comment]
You can have `mumble.users.myself['channel_id']`
if you want to manager the channel, you can use ` channel = mumble.channels[self.mumble.users.myself['channel_id']] `

If you still don't have the `id` , be sure to have pymumble ready : `mumble.is_ready()`

**Comment by WhatsCS** [comment]
I've got `mumble.is_ready()` and the bot is connecting to the mumble server. The bot can also receive messages and that's when I'm testing `mumble.users.myself['channel_id']` which throws `KeyError: 'channel_id'`

**Comment by azlux** [comment]
Can you try the command `print(mumble.users.myself)` before and after sending to the bot a private message ? I've maybe an idea of you problem !

**Comment by WhatsCS** [comment]
On connect/idle: `{'session': 23, 'name': 'TestBot'}`

On message: `{'name': 'TestBot', 'session': 23}`

**Comment by azlux** [comment]
Every "channel" message learn the bot his own channel_id
`
message.parameters = {"session": session,
                           "channel_id": channel_id,
"message": message} 
`
It's my mistake, only Channel message do that, there are no `channel_id` into Private message.
The strange behavior is the server don't send any informative message to the bot when he connect.

**Comment by WhatsCS** [comment]
Yeah, `channel_id` gets sent with a channel message and `session` is sent when private message but that's about it. I suppose we would have to poll the server for the channel or keep track when the bot connects and is moved.

**Comment by azlux** [comment]
Can I speak to you ? I want to understand what to you need. You can join me into my mumble (mumble.crystalyx.net)

**Comment by WhatsCS** [comment]
Sure, I'm available for a couple of hours, I'm on GMT-8 for timezone.

**Comment by azlux** [comment]
After debug with @WhatsCS , there are not `channel_id` value when bot is into the root channel. It's a limitation of the mumur server. I'm looking for a fix.

**Comment by azlux** [comment]
Fix Done !
