### ISSUE TITLE
Module import issue and ssl exception

### ISSUE THREAD

**Issue by JirkaRCK** [azlux/pymumble#18]
I have tried to install pymumble and dependencies:
`python3 setup.py build`
`sudo python3 setup.py install`
`pip3 install -r requirements.txt`

I wanted to try MumbleRadioPlayer to test the library is installed correct. MumbleRadioPlayer crashed on 13th line: There is not module named pymumble.pymumble_py3

After some experiments in IDE, I have tried change the line 13 from: `import pymumble.pymumble_py3 as pymumble` to `import pymumble_py3 as pymumble`. MumbleRadioPlayer turns on now, but while connecting, make this Exception:

`Exception in thread Thread-1:`
`Traceback (most recent call last):`
`  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner`
`    self.run()`
`  File "/usr/local/lib/python3.5/dist-packages/pymumble_py3/mumble.py", line 108, in run`
`    if self.connect() >= PYMUMBLE_CONN_STATE_FAILED:  # some error occured, exit here`
`  File "/usr/local/lib/python3.5/dist-packages/pymumble_py3/mumble.py", line 130, in connect`
`    self.control_socket = ssl.wrap_socket(std_sock, certfile=self.certfile, keyfile=self.keyfile,` `ssl_version=ssl.PROTOCOL_TLS)`
`AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS'`

Please, what am I doing wrong?

**Comment by azlux** [comment]
Good point.

From the doc :
ssl.PROTOCOL_TLS
    Selects the highest protocol version that both the client and server support. Despite the name, this option can select both “SSL” and “TLS” protocols.
    New in version 3.6.

Which version of python3 do you use ?
I forgot to keep the retro-compatibility with python3.5 (you can blame @Lartza for that ) when I've accepted the commit #16 

Thank for the issue, I will check that ASAP.

**Comment by Lartza** [comment]
PROTOCOL_TLS is also available in 3.5.3 and 2.7.13 though and seems to be the default so specifying ssl_version might not even be necessary if one can figure out what 3.5.2 uses as a default.

EDIT: PROTOCOL_SSLv23 is used in previous Python versions so not preferable. Not sure what the cleanest way to fix this is in that case. Maybe check Python version and use PROTOCOL_TLSv1 if 3.5.2 or older. Then people can update their Python to get a higher TLS version.

**Comment by Lartza** [comment]
Actually maybe just do this?
```
try:
    self.control_socket = ssl.wrap_socket(std_sock, certfile=self.certfile, keyfile=self.keyfile, ssl_version=ssl.PROTOCOL_TLS)
except AttributeError:
    self.control_socket = ssl.wrap_socket(std_sock, certfile=self.certfile, keyfile=self.keyfile, ssl_version=ssl.PROTOCOL_TLSv1)
try:
    self.control_socket.connect((self.host, self.port))
...
```

**Comment by JirkaRCK** [comment]
I have actualy installed Python 3.5.2 (default in Ubuntu 16.04). I will try with 3.6.

**Comment by Lartza** [comment]
@JirkaRCK /usr/local/lib/ would indicate you have a manually compiled version of 3.5 at least to me.
But in any case for now you can upgrade to 3.5.3 or any 3.6 version, or change ssl.PROTOCOL_TLS to ssl.PROTOCOL_TLSv1

**Comment by JirkaRCK** [comment]
@Lartza  I have manually installed the pymumble library, I think this is the reason for /usr/local/lib/. I am sure that the Python is installed from official repository by apt-get (I am on my own notebook, I would remember this :-) )

Many thanks for fast help!

**Comment by JirkaRCK** [comment]
UPDATE: You are right - everything works well on Python 3.6. I am connected.

**Comment by azlux** [comment]
https://github.com/azlux/pymumble/commit/62ee7d7bd889ea69ab3727a3b2536ae413181e81 fix the problem for older python3 version (thank @Lartza)
