### ISSUE TITLE
Is there support for creating temporary channels?

### ISSUE THREAD

**Issue by DuckBoss** [azlux/pymumble#22]
If my mumble python bot were to create a temporary channel and join instead of searching for existing channels, is that possible? I don't currently see anything that allows the creation of channels, please let me know =)

**Comment by azlux** [comment]
All mumble management commands arn't implemented into pymumble.
I will look for it next week.

**Comment by DuckBoss** [comment]
Okay, thank you for the quick response!

**Comment by DuckBoss** [comment]
I was just wondering if you looked into this and found anything about management commands?

**Comment by azlux** [comment]
Hi, with the issue closed I forgot about it. Keep it open.
Sorry.
Az

Note to myself : https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/mumble_pb2.py#L606

**Comment by DuckBoss** [comment]
No problem, I will leave this open.

**Comment by azlux** [comment]
Hi.
The feature is almost ready, but I don't know why the server refuse some of my new messages to create channel. 
I will work with mumble develloper on September.

Az
Srry for the delay.

**Comment by azlux** [comment]
Hi @DuckBoss ,
You can try this commit.
the function
`mumble.channels.new_channel(mumble.channels.find_by_name("Name of parent channel").get_id(), "name_ofchannel")`

**Comment by DuckBoss** [comment]
Thanks @azlux , I will try this soon and let you know how it works out.

**Comment by DuckBoss** [comment]
Works as intended.
