### ISSUE TITLE
get_childs() doesn't work

### ISSUE THREAD

**Issue by MrNerdy42** [azlux/pymumble#23]
The get_childs() method raises a KeyError because the Root channel does not have the key 'parent'. Also channel['channel_id'] isn't valid because the channel argument is already an int.

**Comment by azlux** [comment]
You have done the method `get_childs()` with the root channel ? In this case I will add an exception in the next fix.
If it wasn't channel in parameter wasn't the root, can you describe the code/issue ?

**Comment by MrNerdy42** [comment]
Actually I was using it on another channel id. My codes isn't too fancy, I just make a call to get_childs on id 1  (a channel called 'Game' on my sever).

I forked your project to do some debugging and it seems that get_childs iterates through all channels on the sever, including 'Root'

**Comment by azlux** [comment]
> Also channel['channel_id'] isn't valid because the channel argument is already an int.

You need a channel object and not the channel_id into parameter.

In my test, I've use the bot current channel with : 
```
print(self.mumble.channels.get_childs(self.mumble.channels.find_by_name(self.channel)))
```
