### ISSUE TITLE
Targets

### ISSUE THREAD

**Issue by Flupster** [azlux/pymumble#25]
It's mentioned in the README that targets is not implemented, I could have much use for whisper, I know you havn't commited in awhile so no worries if not but would be amazing

**Comment by azlux** [comment]
Hi.
I think it will not that hard to implement it.
I need to write new messages for the server to register/delete whisper.
I will work on it during September.

**Comment by azlux** [comment]
Are you talking about channel whisper or user whisper ?

**Comment by azlux** [comment]
You can use it with : 
`mumble.sound_output.set_whisper(<UserSessionID>)`
The UserSessionID is into `mumble.users["Name"]["session"]`

Remove the whisper with `mumble.sound_output.remove_whisper()`

As Mumble, you can have multiple peoples to target (you can give a list as parameter)

Az

**Comment by Flupster** [comment]
Amazing, any possibility for channel ids also, with that done also i believe it's feature complete on targets, there's nothing in mumble other than shout, whisper to channel(s) whisper to user(s)

**Comment by azlux** [comment]
Yes, it's possible for other channel to implement it, not a big deal since the whisper is implemented.
Maybe next week.

**Comment by azlux** [comment]
I really need to have a todo list. I've forgot about this issue.

**Comment by azlux** [comment]
Hi @Flupster 
You can now use : 
For whisper to one user : `mumble.sound_output.set_whisper(<session_id>)`
For whisper to multiple users : `mumble.sound_output.set_whisper([list of session_id])`
For whisper to one channel : `mumble.sound_output.set_whisper(<channel_id>, channel=True)`
You cannot whisper into multiple channels (mumble limitation)
