### ISSUE TITLE
Trying to understand recording

### ISSUE THREAD

**Issue by TchGimmick** [azlux/pymumble#26]
I'm doing my best to understand and use this code, but I've been banging my head over bits and pieces for quite a while. Perhaps someone could shed some light on it for me.

My Primary Goal: To drive a GPIO pin on a raspberry pi whenever anyone in a specific channel is speaking.

I've managed to connect to a server, move to a specified channel, and determine if a user is connected or not to. As well as be notified if anyone connects/leaves/updates in the future.

I also wrote some pretty dirty/clumsy code that will drive a GPIO pin when someone is talking. I do this using the PYMUMBLE_CLBK_SOUNDRECEIVED callback.

What I've not been to do is empty any buffers in the library that are building up when speaking is happening. I just can't seem to figure out how to do that. Any help with this would be greatly appreciated.

Ultimately, I would like to record what happens in a channel to MP3 or some other compressed audio format, but right now, I'd settle for knowing how to clear the buffers. I've tried to understand MumbleRecBot, but I keep getting confused, especially since it doesn't seem to work with pymumble for python 3.

Thanks! - Tim D.

**Comment by azlux** [comment]
Hi @TchGimmick .
I don't have currently any example for recording.
MumbleRecBot is the only bot I know how record with pymumble.
Things I see into the bot is after this line : https://github.com/Robert904/mumblerecbot/blob/master/mumblerecbot.py#L186
You need to check every buffer. With mumble, you receive a separated channel for each user. (see L213)
Have you any error ?

Az

**Comment by jackdweber** [comment]
TchGimmick, were you ever able to receive audio on pymumble3? I cannot seem to get it to work. The Sound received callback is never called, and it seems like the sound queues for every user are always empty.

**Comment by azlux** [comment]
@jackdweber Have you a code/program I can check/test ?

**Comment by jackdweber** [comment]
Thanks for the quick reply!
I seem to have got it working, like the MumbleRecBot, I was looping on mumble.is_alive(). when I do not do this, and just use the callback it seems to work. I can get the user and sound byte from the callback, which is all the info I need. (Trying to make a wifi walkie-talkie with a raspberry pi)

**Comment by azlux** [comment]
@jackdweber Are you waiting for the bot to be ready ? Weird that is_alive stop the loop.

Az

Ps : I'm on freenode is you need help

**Comment by jackdweber** [comment]
I was just following the pattern in the recbot. It seemed like it would use the is_alive loop to check all the user sound queues. I think the callback will work for me since it sends the sound it receives. I need to have all the sounds play in real time, so I will probably build/mix my own global sound queue based on those sounds received.

**Comment by TchGimmick** [comment]
I know someone asked if I had solved what I was working on. And unfortunately, I have not. Also, I just don’t have time to work on that project at this point in my life. It is an ongoing project, so I will keep an eye on this conversation.

Thank you all for being so helpful. I wish I had some knowledge to offer to those seeking solutions.

 

*	Tim D.

**Comment by azlux** [comment]
Is someone want me to test your code ?
I done make recording, but I can help to debug.

**Comment by azlux** [comment]
You can check the new example !
https://github.com/azlux/pymumble/blob/pymumble_py3/examples/

Thank a lot @farooqkz !

**Comment by farooqkz** [comment]
You are welcome!

**Comment by balkan16** [comment]
> My Primary Goal: To drive a GPIO pin on a raspberry pi whenever anyone in a specific channel is speaking.

> I also wrote some pretty dirty/clumsy code that will drive a GPIO pin when someone is talking. I do this using the PYMUMBLE_CLBK_SOUNDRECEIVED callback.
 

Hello @TchGimmick, I know it's been a long time since this issue opened, but recently, I did some holiday project with mumble and a raspberry pi which apparently had the same primary goal as yours. Do you still have it and don't mind if I experiment with it?

**Comment by TchGimmick** [comment]
You are more than welcome to experiment with what I have. It’s been years since I’ve touched it. I never got what I wanted to work. If you get anywhere with it, please let me know!

 

-TimD.

**Comment by balkan16** [comment]
Sure thing, thank you!
