### ISSUE TITLE
Unable to send images?

### ISSUE THREAD

**Issue by DuckBoss** [azlux/pymumble#27]
Hello!
I've been trying to send image data in the chat but I keep hitting the 5000 maximum character limit when using channel.send_text_message().
Is there any way to do a channel.send_image() to send image data instead?

**Comment by azlux** [comment]
Hi
The limitation is hard-coded here : https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/mumble.py#L94
The server can override this value https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/mumble.py#L428 but I'm not sure current servers are doing it. I need to speak with the sever developers.

Az

**Comment by DuckBoss** [comment]
Thanks for the help! I am currently using a private mumble server so I can override the value as needed.

**Comment by azlux** [comment]
Hi,
Please reopen the issue.
There are one bug here (You have close it when I was reading the mumble protocol)
In mumble, when you send image, it doesn't follow the same limit.
If you check the murmur configuration, you will have : 
- textmessagelength (for text only, 5000 by default)
- imagemessagelength (for text + image , 131072 by default)

I've checked, pymumble use only the textmessagelength.
So I need to implement the image limit.

Az

**Comment by DuckBoss** [comment]
Okay thanks for bringing up this bug. Some images under 10kb worked with the current system but anything over that limit crashed the python program.

**Comment by azlux** [comment]
Can you give me the error ?

**Comment by DuckBoss** [comment]
I wasn't able to retrieve any error from the crash. The script froze until it eventually crashed. It doesn't seem to be consistent with how it crashes either. I'm currently trying a work-around by publishing an image to the web and using its urls to post in the channel chat via html tags since that would be under the 5000 character limit.

**Comment by DuckBoss** [comment]
I will check the commit tomorrow and let you know how it works out.

**Comment by DuckBoss** [comment]
Works as intended! Thanks!
