### ISSUE TITLE
pymumble sound output question

### ISSUE THREAD

**Issue by DuckBoss** [azlux/pymumble#28]
I noticed in your botamusique pymumble implementation, you used the ffmpeg subprocess to output the pcm data to stdout=PIPE, and then use pymumble to read the stdout data. Is something like this possible with a different player like VLC for python? 

For example, I can use the python vlc library to output audio to stdout, but is it possible to retrieve that audio and read it for pymumble to use? Since the python vlc library would not be a subprocess, I can't use stdout=PIPE as far as I know.

Do you have any thoughts or suggestions?

**Comment by azlux** [comment]
Hi @DuckBoss .
If you want pymumble to access a flux, you need to read it from a pipe.
VLC can redirect audio through stdout (`--sout file/<some mux>://-`).

I don't really understand what you want to achieve with VLC. Why VLC cannot be a subprocess ?
You can check the project https://github.com/ranomier/pymumble-abot/blob/master/abot.py it use input stream.

Az

**Comment by DuckBoss** [comment]
I wanted to have finer control over the process through a python vlc library so I didn't want to subprocess the vlc program. I tried using the sout parameter in vlc but I couldn't figure out how to use that pipe as an input for the pymumble sound output api. According to your botamusique implementation, you use a subprocess and use mumble.sound_output.stdout.read(buffer_size) to read the audio data from vlc. However I was wondering if it was possible to read stdout data from vlc when it is not initialized as a subprocess and instead through a vlc python library with the sout parameters.

Am I just going about this the wrong way?

**Comment by DuckBoss** [comment]
I figured out the problem with the way I was approaching my problem. Thanks for helping me earlier with the --sout commands.
