### ISSUE TITLE
Connection with certificate fails

### ISSUE THREAD

**Issue by julr** [azlux/pymumble#3]
I am trying to connect to a server with a certificate I exported from the mumble client and the "certfile" parameter. But shortly after I call the start() function the pymumble thread just terminates without any message. Here is the test code I am using:

``` python
import sys
import os
import time

sys.path.append(os.path.join(os.path.dirname(__file__), "pymumble"))
import pymumble

HOST = "localhost"
PORT = 64738
USER = "PyMumble"
PASSWORD = ""
CERT = "client-export.p12"

mumble = pymumble.Mumble(host=HOST, port=PORT, user=USER, password=PASSWORD, certfile=CERT, debug=True)

mumble.start()
mumble.is_ready()
time.sleep(0.1)
print(mumble)
```

And this is the output I get:

> 2016-08-27 09:35:03,855-PyMumble-DEBUG-connecting to localhost on port 64738.
> <Mumble(Thread-1, stopped 12344)>

No connection to the server is made in this case.

When I remove the cerfile parameter it works as expected.

**Comment by Xefir** [comment]
Hello.

For now, you have to point a valid OPENSSL certificate (usually pem or crt) and not a Mumble generated p12 file.
You can convert between the two with this command line : `openssl pkcs12 -in keyStore.p12 -out keyStore.crt -nodes`

Please find all of the usefull commands here : https://www.sslshopper.com/article-most-common-openssl-commands.html

**Comment by julr** [comment]
Thanks. Now it works.

**Comment by pramadhana92** [comment]
Hello all, I know it's a closed topic.

I know that we can get certificate using certificate wizard in mumble, or by openssl command in linux which is mentioned by @xefir.

But I'm a windows user. Also I want to do all things **pure in python.**
After experimenting several times, I found a way to generate certificate using python script and it is working fine in pymumble.

Here is the script: (maybe @duckboss would like to see this script)

```
from OpenSSL import crypto, SSL

NAME = input("set certificate subject/issuer: ")
CERT_FILE = "cert.pem"
KEY_FILE = "key.pem"

# create a key pair
key = crypto.PKey()
key.generate_key(crypto.TYPE_RSA, 2048)

# create a self-signed cert
cert = crypto.X509()
cert.get_subject().CN = NAME
cert.get_issuer().CN = NAME
cert.set_serial_number(1000)
cert.gmtime_adj_notBefore(0)
cert.gmtime_adj_notAfter(10*365*24*60*60)
cert.set_issuer(cert.get_subject())
cert.set_pubkey(key)
cert.sign(key, 'sha1')

# write cert and key file
open(CERT_FILE, "wb").write(crypto.dump_certificate(crypto.FILETYPE_PEM, cert))
open(KEY_FILE, "wb").write(crypto.dump_privatekey(crypto.FILETYPE_PEM, key))
```

[reference](https://stackoverflow.com/questions/27164354/create-a-self-signed-x509-certificate-in-python)

use the file in pymumble argument:
`pymumble.Mumble(......,certfile="cert.pem", keyfile="key.pem")`

now the bot can be registered in server.

**notes: you need to install PyOpenSSL package to run this script**

**Comment by DuckBoss** [comment]
> Here is the script: (maybe @DuckBoss would like to see this script)

Thanks for tagging me. for my mumble bot I call the system openssl installation instead of using a python package, but this is interesting and might be more reliable across platforms. Thanks for bringing this to my attention 👍
