### ISSUE TITLE
Is there a method to rename channels?

### ISSUE THREAD

**Issue by DuckBoss** [azlux/pymumble#31]
I've made a bot and it can make channels, but I haven't found a way to rename channels created by the bot. Is there a way to rename channels you've created through the pymumble api?

**Comment by azlux** [comment]
Hi.

Pymumble don't have admin fonctions. That is why you don't find the method. It doesnt exist.

**Comment by pramadhana92** [comment]
I create rename channel feature in here:
**Channel Administration** #93
