### ISSUE TITLE
A shortcut for client's channel

### ISSUE THREAD

**Issue by farooqkz** [azlux/pymumble#35]
I think this library needs a shortcut to client's own channel. Now, it is accessible through mumble.users.myself['channel_id']

**Comment by azlux** [comment]
`mumble.channels[mumble.users.myself['channel_id']]` to be exact

**Comment by DuckBoss** [comment]
In the <a href="https://github.com/DuckBoss/JJMumbleBot">bot I made</a>, I simply made a wrapper for simpler use:
```
def get_my_channel(mumble):
    return mumble.channels[mumble.users.myself['channel_id']]
```

**Comment by farooqkz** [comment]
In this case it should something like:
```
def my_channel(self):
    return self.channels[self.users.myself["channel_id"]]
```
