### ISSUE TITLE
Getting input from a different channel?

### ISSUE THREAD

**Issue by DuckBoss** [azlux/pymumble#37]
Hello! I have a bot setup that can send commands to the bot through 
the 'message_received ' callback which works for private message and channel messages.
Is there a way to send messages to the mumble instance from a different channel without private messaging? (Similar to how whisper can send data to other channels)

**Comment by azlux** [comment]
The title of this issue is "Getting input" but the message is "a way to send messages".
Can you explain you case ? I don't understand the question.
You want to send a message to a different channel than yours, or you want to get a message send no on your channel ?

Az

**Comment by DuckBoss** [comment]
Sorry for the confusion, I was wondering if it is possible to use the pymumble API to detect messages sent in other channels. So if my bot made with the pymumble library was in a different channel, is there a way for it to detect messages in my channel (without private messaging)?
I don't know if mumble allows this, but I wanted to check with you.


Does this make sense?

**Comment by azlux** [comment]
It's not possible to have message not intended to you or your channel.
That is a security issue, not allowed by mumble.

The only way to have similar feature, is using recursive channel message, or writing a mumo script.

**Comment by DuckBoss** [comment]
Okay thanks. I was hoping there would be a work around somewhere.
