### ISSUE TITLE
Registering pymumble clients on servers

### ISSUE THREAD

**Issue by DuckBoss** [azlux/pymumble#41]
Hi!
Is it possible to register a pymumble bot on a server that allows self-registration?
I'm trying to find a way to automatically register my bot on a private server.
If that's not possible, is there a config or something where I can add the client username to register?

Currently the only method of registering the bot is for an admin server user to register it manually.

**Comment by azlux** [comment]
Hi,

Srry, I've skip this issue,
I didn't saw the notification.
It's currently impossible, I will check for the implementation.
Update in few days.

Az

**Comment by azlux** [comment]
Ok,
I've discuss with people on IRC, should be not hard to implement,
It's just the UserState message to modify.

Reminder : 
[client code](https://github.com/mumble-voip/mumble/blob/628c067034f598c0e2dd8ca5a1e28b551118986c/src/mumble/ServerHandler.cpp#L854-L859)
[protobuff message](https://github.com/mumble-voip/mumble/blob/628c067034f598c0e2dd8ca5a1e28b551118986c/src/Mumble.proto#L179)

**Comment by azlux** [comment]
You can use  `user.register()`
You need a certificate to make it work.

Azlux

**Comment by DuckBoss** [comment]
Awesome, thanks!

**Comment by azlux** [comment]
Do you need a way yo know if the bot is already registred ?

**Comment by DuckBoss** [comment]
That would be helpful if you can add that.

**Comment by azlux** [comment]
ok, the function already exist:

`mumble.users.myself.get_property('user_id')` is None is the user isn't registered. It's a number if registered.

Do you prefer a real function like (`mumble.users.myself.is_registered()`) ?

**Comment by DuckBoss** [comment]
Thanks for your help. I don't think the function is_registered() would be required for my functionality, but there might be others who would like it.
