### ISSUE TITLE
Have problem running talking_bot.py on Raspberry Pi 3B+ (Raspbian Buster, kernel version 4.19)

### ISSUE THREAD

**Issue by FanchenBao** [azlux/pymumble#42]
Actually I have one comment and one question.

**Comment**: When I tried to run `talking_bot.py` initially (latest Raspbian Buster, kernel version 4.19), I got this error ` [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)` (it is not displayed by default. I have to dig into `mumble.py` to print out `socket.error` in `connect()` function). To resolve this, I have to manually change `MinProtocol` in this file `/etc/ssl/openssl.cnf` from `TLSv1.2` to `TLSv1.0` to make the connection work. I suppose this might be helpful information for others.

**Now question**: When I was running `talking_bot.py`, I couldn't hear any sound. I used a headphone and had checked audio was directing to the 3.5 mm jack. To show that other functionalities of `talking_bot.py` were working, I connected another mumble client to the same server on my laptop, and I could hear the speech generated by RPi. So there was no problem with generating and sending sound to the server. So what is preventing me from hearing the sound on RPi (note: when I run `talking_bot.py` on my laptop, I can hear the sound on the same laptop as well)?

Thanks all in advance.

**Comment by azlux** [comment]
Hi,
I also have some questions:
- The ssl error is a known issue from Debian 10 (buster) because TLSv1.0 is disabled by default.
The pymumble use the standars system librairie. So If you mumble server is version 1.2.x and your pymumble client on debian buster, you hit this issue.
 **Please upgrade you mumble server to version 1.3** (up-to-date on Buster) 
- What is your script `talking_bot.py` ? I've never heard about it.
It's look like a Rpi or talking_bot issue.

Az

**Comment by FanchenBao** [comment]
Hi,

* Thank  you very much for speedy reply and the explanation of the ssl issue. It must be the server problem then. I was using a free online mumble server, which most likely is not up-to-date.
* I was running the `talking_bot.py` straight from the `examples` folder on the repo. I think my question is: can the machine (be it RPi or laptop) running `talking_bot.py` be able to listen to the sound generated? Given that there is no callback set up for receiving sound from server, I now suspect the code is not set up to let the machine running the script hear the sound.

**Comment by azlux** [comment]
I indeed forgot the example here.
They come from @farooqkz .
talking_bot take input to text-to-speech in the mumble server. It's the only action it do.

I know abot (https://github.com/ranomier/pymumble-abot) can do alsa-> mumble.

See a deprecaded bot, but have good implementation for mumble->recording:
https://github.com/Robert904/mumblerecbot/blob/master/mumblerecbot.py#L186
https://github.com/Robert904/mumblerecbot/blob/master/mumblerecbot.py#L219-L239

I've never done such bot. But I can help if you have any question

**Comment by FanchenBao** [comment]
After some more digging, I have a better understanding of `pymumble`. I originally had the impression that `pymumble` can process sound recording and playback, but those were not part of its functionalities. I have made `talking_bot.py` work the way I desire by using `pyaudio` to manage sound playback.

**Comment by azlux** [comment]
Hi,
I've you have a script for a listener/recorder bot, you can make a pull request to add it into the example.
It's will be a pleasure to add it.
Az

**Comment by FanchenBao** [comment]
I can open a PR to add an example of audio-only mumble client supporting verbal communication with another mumble client running on a separate device.

**Comment by FanchenBao** [comment]
#43
