### ISSUE TITLE
Memory leak in SoundQueue.add

### ISSUE THREAD

**Issue by stblassitude** [azlux/pymumble#44]
I have a script that receives audio through a callback and analyses it continuously. I've noticed that memory increases constantly. After some debugging with objgraph, it appears that somehow the SoundChunks added to the queue in line 60:
```
self.queue.appendleft(newsound)
```
will never leave the queue.

I've tried to empty the queue in the callback, but that doesn't appear to be working.

I'm wondering if the sound should be added to the queue at all if the `PYMUMBLE_CLBK_SOUNDRECEIVED` callback is used. And is the code to reorder the sound chunks really necessary, since all data arrives over TCP?

For now, I've forked the module and commented out the block that deals with filling the queue.

**Comment by azlux** [comment]
Hi, 
This code exist for futur UDP transport. You can keep is as comment.
I haven't figure how to send UDP yet. Encryption is hard to implement.

You can open a Pull requests if you want.

**Comment by azlux** [comment]
Hi,
I've read the changes you have done.
Can you give me an example of your code ?

Reorder is for a futur use, but you should keep the `self.queue`
It's used on for [some functions](https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/soundqueue.py#L92) . When you get sound, the function should clear this queue.

I'm reading the code, and you're right, callback use the return of the function add. And never clear the queue. That the goal of a callback, you don't know when sound will be manage.

What if I add a function to clear manually the queue buffer ?

**Comment by azlux** [comment]
@farooqkz You will have the same issue on your echo.py bot.

**Comment by azlux** [comment]
@stblassitude this commit will not store voice data is a callback is used. Should fix your issue.
