### ISSUE TITLE
Disable text-to-speech

### ISSUE THREAD

**Issue by SundayVermillions** [azlux/pymumble#47]
Is there any way to disable text-to-speech programmatically? I've tried looking into a solution server-side, but apparently [it's only possible to do so client-side, via the GUI](https://github.com/mumble-voip/mumble/issues/2679)

**Comment by azlux** [comment]
Hi,
As you have read, Text-to-speech is a GUI parameter.
Why did you open an issue on pymumble ? It's not the mumble GUI repo, and there are no text-to-speech in this project.

**Comment by SundayVermillions** [comment]
Hi azlux, 

yes, I'm aware of that. I was just wondering if there was a way to disable or filter out the server-side text-to-speech notification sounds (eg. "User has joined the channel", "User has disconnected") on the client-side using the pymumble library, since the same thing is possible using the original Mumble client GUI. I would like to avoid setting this through the GUI application as far as possible since I'm using this for an embedded system. 

My apologies if I wasn't clear on what I was asking. If there's no possible way to do it through pymumble, I'll proceed to close this issue.

on a side note, thanks for maintaining this! it's really been a great help thus far.

**Comment by azlux** [comment]
It's not possible, It's a  configuration of each GUI client you need to do.
The sound come from a notification based on incoming people/message information. It's no specific sound message send from another client.

No need for apologies, It's encouraging to see other people asking questions.
