### ISSUE TITLE
Mumble ready_lock not released

### ISSUE THREAD

**Issue by ChamNouki** [azlux/pymumble#56]
I face an issue with pymumble when mumble server is not available or when internet connection is not available (and mumble server not on localhost). The exception is raised from the `connect` method in the Mumble object.

On those cases, the pymumble thread object terminate with error. I think that since the error is not catched, the `ready_lock` in the Mumble object is not released. Since my main process is waiting for connection with the `is_ready` method all my program is totally blocked.

**Comment by azlux** [comment]
You're right, I've observe the same on my side. I will check that.
Thanks for the report. (And for the waiting, I quite slow)

**Comment by azlux** [comment]
Can you check now, should be fix.
