### ISSUE TITLE
Mumble disconnection callback

### ISSUE THREAD

**Issue by ChamNouki** [azlux/pymumble#57]
Could it be possible to have a PYMUMBLE_CLBK_DISCONNECTED like the PYMUMBLE_CLBK_CONNECTED one ?

**Comment by Lindenk** [comment]
Also it doesn't seem like there is even a way to disconnect. That seems like a rather important feature

**Comment by azlux** [comment]
@Lindenk indeed. To disconnect, you need to kill the mumble object.
@ChamNouki I'm agree this callback isn't available. Current implementation stop the socket once the mumble object is disconnect. You want a callback to have reconnection actions ?

**Comment by azlux** [comment]
Can you check now, should be fix.

**Comment by wasauce** [comment]
@azlux - what do you mean kill the mumble object? 

What would the preferred way to do this be please? We currently just let it timeout. But I'd be happy to set it to None or some other method to kill the object when we are done processing.

**Comment by azlux** [comment]
@Lindenk @wasauce After digging, I've create a separate issue because I need to add some code. https://github.com/azlux/pymumble/issues/61

**Comment by ChamNouki** [comment]
PYMUMBLE_CLBK_DISCONNECTED seems to work perfectly. Even though PYMUMBLE_CLBK_CONNECTED is not called when connection is back. Trying to find why but it seems that we never pass in the `if` at line 314 in mumble.py and I don't understand why.

**Comment by ChamNouki** [comment]
Not passing in the `if` at line 314 in mumble.py seems to be link to #63

**Comment by azlux** [comment]
can we follow this issue on #63 ?

**Comment by ChamNouki** [comment]
sure we can ^_^
