### ISSUE TITLE
user.sound_set_receive_sound lead to crash

### ISSUE THREAD

**Issue by boyska** [azlux/pymumble#60]
I'm writing a bot in which I want to listen all users in a channel *except* some, and stream them all to a sound device.

What I'm doing is:

```py
for uid, user in mumble.users.items():
    if user.get("name", False) not in args.ignored_users:
        continue
    user.set_receive_sound(False)
```

This leads to this crash happening whenever one of the ignored users talks.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/luser/.local/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 120, in run
    self.loop()
  File "/home/luser/.local/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 197, in loop
    self.read_control_messages()
  File "/home/luser/.local/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 271, in read_control_messages
    self.dispatch_control_message(type, message)
  File "/home/luser/.local/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 277, in dispatch_control_message
    self.sound_received(message)
  File "/home/luser/.local/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 498, in sound_received
    sequence.value += int(round(newsound.duration / 1000 * 10))  # add 1 sequence per 10ms of audio
AttributeError: 'NoneType' object has no attribute 'duration'
```

Some more info that might be useful:
 * the "global" `mumble.set_receive_sound(False)` works fine (but does not do what I want)
 * if any other users talks, there is no crash. the crash happens when one of the "ignored" users talks

If you need any other info, let me know

**Comment by azlux** [comment]
I think you've misunderstood the `set_receive_sound` function.
This option is to order the bot to treat incoming audio. This cannot be specified for each users.

You can use callback to apply a 
function when you receive sound and filter the user you want. Or you can have a loop looking for sound for each users.

**Comment by encrypt94** [comment]
Hey, i think he is talking about the `SoundQueue.set_receive_sound` function that looks like an user specific mute.

The crash seem caused by an incorrect handling of the `None` returned by [SoundQueue.add](https://github.com/azlux/pymumble/blob/1dd6d6d4df2fdef33202f17e2acf3ba9678a5737/pymumble_py3/soundqueue.py#L43)
You can fix that adding `if newsound is None: return` [here](https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/mumble.py#L498)

**Comment by azlux** [comment]
@encrypt94 You're right, you have analyzed the issue correctly.

**Comment by azlux** [comment]
Can you check now, should be fix.

**Comment by encrypt94** [comment]
Works  for me! thanks for the fix!
