### ISSUE TITLE
Untimely connecting and disconnecting from server when using reconnect 

### ISSUE THREAD

**Issue by ChamNouki** [azlux/pymumble#63]
When using the reconnect feature, after loosing connection to the server a first time, ping action always lead to set `connected` flag to `PYMUMBLE_CONN_STATE_NOT_CONNECTED` state (mumble.py line 219) after some iteration of the `while` loop in the `loop` function (mumble.py line 186). Following continuous socket closing and reopening.

This is all the more strange since I see my bot connected on the mumble server in the mumble application.

It seems that pymumble does not pass anymore the `if` statement of the `dispatch_control_message` method for the `PYMUMBLE_MSG_TYPES_SERVERSYNC` message type (mumble.py line 314). However the `connected` flag is well set to `PYMUMBLE_CONN_STATE_AUTHENTICATING` when trying re-connection, Despite this the ping method set it to `PYMUMBLE_CONN_STATE_NOT_CONNECTED` before the `PYMUMBLE_MSG_TYPES_SERVERSYNC` message arrive.

**Comment by azlux** [comment]
The issue you describe here is when you loose a mumble connection or use the stop feature ?
You should have error during the run, do you have it ?
Do you see the bot connected on mumble server when it try to re-connect ?

**Comment by ChamNouki** [comment]
The issue I described happens when pymumble loose mumble server connection (I do not use stop feature yet in my project by the way).
I didn't see any error during the run.
I clearly see the bot connected on mumble server, then disconnected and connected again etc.

**Comment by azlux** [comment]
Is my last commit improve the situation ?

**Comment by ChamNouki** [comment]
Yes it is !! The mumble server stay connected after re-connection, good job :D

Unfortunately there is another issue with the reconnect feature that make the wall thread crashing.

When the connection is lost because host machine lost it's network connection, after a few seconds pymumble retry connection fail with the following error :
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/thibaut/Documents/GitHub/Mumgram/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 114, in run
    if self.connect() >= PYMUMBLE_CONN_STATE_FAILED:  # some error occurred, exit here
  File "/Users/thibaut/Documents/GitHub/Mumgram/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 134, in connect
    server_info = socket.getaddrinfo(self.host, self.port, type=socket.SOCK_STREAM)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

And when the mumble server is down the pymumble retry connection fail with the following exception a few seconds after being disconnected :
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/thibaut/Documents/GitHub/Mumgram/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 116, in run
    raise ConnectionRejectedError ("Connection error with the Mumble (murmur) Server")
pymumble_py3.errors.ConnectionRejectedError: 'Connection error with the Mumble (murmur) Server
```

So it seems to be a problem when the connection is lost more than a few seconds. But this could be consider as another issue ?

**Comment by azlux** [comment]
The first error is when the internet is disconnected, the DNS cannot be resolve.
The second is weird, the host have been resolve but the lib isn't able to establish a socket, maybe your connection isn't really ready at this point and the lib said there a an issue.

I'm not sure we need to fix this specific case. That will be the propose of the bot, to wait and call the Mumble class again.

**Comment by ChamNouki** [comment]
Yes, I disabled the network connection of my bot host and exited the Mumble server, respectively.

Reading your message, it is quite possible that I misunderstand the functionality behind the Mumble class reconnection flag. Could you explain to me how it works?

**Comment by azlux** [comment]
See https://github.com/azlux/pymumble/pull/65
My message is more about : When you have long disconnection, sometime having the bot stop is better than having a finite try.

But since reconnect is an option, I suppose I can merge the pull requests.

**Comment by azlux** [comment]
I'm merging the #65 commit, and release the new version.

**Comment by ChamNouki** [comment]
It works like a charm 👍
