### ISSUE TITLE
sound_output.flush()

### ISSUE THREAD

**Issue by kousu** [azlux/pymumble#64]
I am trying to write a simple sound effects bot. When disconnecting, I want to make sure I've flushed all the audio data before disconnecting. With Unix files I can do:

```
for i in datasource:
  file.write(process(i))
file.close()
```

But I can't do the same with pymumble, because the equivalent is

```
for buf in audiosource:
  client.sound_output.add_sound(buf)
client.stop()
```

file.close() flushes before returning, but client.stop() doesn't; because the networking is done on a separate thread when my script gets to `.stop()` my audio just gets cut off like it's being strangled.

I would appreciate having a `sound_output.flush()` which blocks until all audio has drained, and for `.stop()` to make sure to call it.

**Comment by kousu** [comment]
Currently I'm just busywaiting:

```
while client.sound_output.pcm: time.sleep(1)
```

and that seems to work, but I'm pretty sure it's not thread safe and there will be ways for it to miss an in-progress `.add_sound()` if the main thread wakes up in the middle of another thread's `.add_sound()`.

**Comment by azlux** [comment]
you current implementation is working without issue.
PCM is the current buffer processed for the mumble socket. If empty, it's means everything is send.

BTW: I don't really understand what you are trying to achieve with that.
