### ISSUE TITLE
Stream exception on receiving audio data from mumble server Raspberry Pi

### ISSUE THREAD

**Issue by Superguy2876** [azlux/pymumble#67]
I'm trying to bridge multiple remote audio networks using mumble. Which might also be interacted with by uses through smartphones or desktop clients.

It seemed to be working initially, as i got sound through to the headset i setup on the pi. But now I am getting the following error whenever i receive audio data from the mumble server.

`Expression 'stream->playback.pcm' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4453
Expression 'alsa_snd_pcm_poll_descriptors_revents( self->pcm, pfds, self->nfds, &revents )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3659
Expression 'PaAlsaStreamComponent_EndPolling( &self->capture, capturePfds, &pollCapture, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3876
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4423
Traceback (most recent call last):
  File "app.py", line 83, in <module>
    data = stream.read(CHUNK, exception_on_overflow=False)
  File "/home/ubuntu/pymumble/lib/python3.8/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9999] Unanticipated host error`

**Comment by Superguy2876** [comment]
In case anyone reads this with the same problem. There seems to be an issue on raspbian with using the same stream in pyAudio to do both input and output. 

I have worked around this by setting up 2 streams instead, one to handle input and one to handle output. As following:

```
CHUNK = 1024
FORMAT = pyaudio.paInt16  # pymumble soundchunk.pcm is 16 bits
CHANNELS = 1
RATE = 48000  # pymumble soundchunk.pcm is 48000Hz

p = pyaudio.PyAudio()
streamRead = p.open(format=FORMAT,
                channels=CHANNELS,
                rate=RATE,
                input=True,  # enable talk
                output=False, 
                input_device_index=3, #The index of my Microphone, may be different in other cases
                frames_per_buffer=CHUNK,
                )

streamWrite = p.open(format=FORMAT,
                channels=CHANNELS,
                rate=RATE,
                input=False, 
                output=True,  # Enable listen
                output_device_index=4, #The index of my Speaker, may be different in other cases
                frames_per_buffer=CHUNK,
                )
```

**Comment by azlux** [comment]
Thanks for the solution. I miss my notification when you have open this ticket. Srry for that.
