### ISSUE TITLE
is it support Acoustic Echo Cancellation?

### ISSUE THREAD

**Issue by EnterTang3** [azlux/pymumble#71]
when a mumble client make phone call in pymumble, it will hear itself's voice

**Comment by TerryGeng** [comment]
No. AFAIK pymumble is designed for general purposes. It is not customized to process human voice.

Also, echo cancellation is a dedicated thing. You need the original voice (echo signal) to tell the canceller what to remove. I think the best way of doing echo cancellation is to use a 3rd party library and forward the processed voice data into pymumble.

**Comment by EnterTang3** [comment]
> No. AFAIK pymumble is designed for general purposes. It is not customized to process human voice.
> 
> Also, echo cancellation is a dedicated thing. You need the original voice (echo signal) to tell the canceller what to remove. I think the best way of doing echo cancellation is to use a 3rd party library and forward the processed voice data into pymumble.

ok，Thank you for Answer

**Comment by azlux** [comment]
Since Terry have already answer, I will close this issue.
Today I saw some projet about noise reduction like this one : https://github.com/xiph/rnnoise Maybe this can help you into your project.
