### ISSUE TITLE
Link and Unlink Channel function

### ISSUE THREAD

**Issue by pramadhana92** [azlux/pymumble#77]
Hi developer pymumble!
This library is really helping me to do automatic administartion such as mute user, deafen user, and many more..

I have read the source code, but i dont find any function to **link channels** and **unlink channels**.

Sometimes when we use link channel in mumble, we forgot to unlink it, and we forgot what channels which still linked..

can you add a feature to unlink channels?
also if we have unlink channel feature, should we have link channel feature?

thanks a bunch!

**Comment by azlux** [comment]
Administration task aren't implemented.
Since some people already ask some new feature (like https://github.com/azlux/pymumble/issues/41, https://github.com/azlux/pymumble/issues/31, https://github.com/azlux/pymumble/issues/25 and https://github.com/azlux/pymumble/issues/22) , I will add that into my todo list.

One question, for management purpose, why don't you use [Mumo](https://github.com/mumble-voip/mumo) ?

**Comment by pramadhana92** [comment]
Wow.. you have so many todo list. Keep up the good work!

umm.. can you give me the hint, how to use mumble_pb2? 
i tried to create the unlink function alone, but i still didnt get it what is messages.py, how to link it with mumble_pb2.py

I dont know about Mumo.. i just try to read one by one of mumble 3rd party.. I'll try to read it..
Thanks for your reply, i really appreciate it!

**Comment by pramadhana92** [comment]
Hi azlux, i think mumo is not created for channels management

but.. i finally created my unlink function alone!
i understand now about how to use mumble proto in mumble.py

thanks azlux and other developer of pymumble!

**Comment by azlux** [comment]
@pramadhana92 wow, that was fast. 
If you have the feature, can you create a Pull request ? I think some people maybe interested by that.

**Comment by DuckBoss** [comment]
I'm also interested, might be able to implement some cool admin features to my bot with this =)

**Comment by pramadhana92** [comment]
@azlux i've research about the function for about 3-4 hours
but before i was already read several parts of pymumble source code

btw.. actually i dont know how to make pull request (sorry i'm still newbie in github)
i'll read how to make a pull request.. please wait okay..

**Comment by pramadhana92** [comment]
okay done!
sorry for making 2 issues..
actually this is my first time making a branch and making a pull request

thanks!
