### ISSUE TITLE
setup.py failing due to renamed package directory

### ISSUE THREAD

**Issue by joschauer** [azlux/pymumble#8]
It seems like the renaming of the `pymumble` directory to `pymumble_py3` broke the setup script.

Should be easily fixable by either renaming it back or changing the packages entry in the setup.

**Comment by azlux** [comment]
thank, I need to take a look at the setup.py

**Comment by azlux** [comment]
I've rewrite the setup.py. but after few research the best way to install it with python3 is with the requirement.txt
