### ISSUE TITLE
How to execute code after finish audio from Mumble

### ISSUE THREAD

**Issue by sp2ong** [azlux/pymumble#81]
Hi,

Based on the example with pymumble I made a script for sending stream from Mumble via UDP to another applicatipon.
via UDP stream audio from Mumble to another application.
Uploading works but I have one problem. When the audio from Mumble is over and the UDP stream is finished, I need to send one UDP packet to the external application and the stream ended.
I can't put this code in "def sound_received_handler(user, soundchunk):"  because this code works when the audio stream is streaming from Mumble and when there is no audio the code is not executed.
How to perform a send / code execution after audio completion with Mumble.

Thanks for any suggestion

```
def sound_received_handler(user, soundchunk):
 .... **code to send via UDP stream**
.....

mumble = pymumble_py3.Mumble(server, nick, password=pwd, port=port)

mumble.callbacks.set_callback(PCS, sound_received_handler)

mumble.set_receive_sound(1)  # Enable receiving sound from mumble server
mumble.start()
mumble.is_ready()  # Wait for client is ready
```

**Comment by sp2ong** [comment]
It will be useful get information about "push to talk" status when start stream audio from mumble PTT is True and when user stop talk PTT is False

**Comment by azlux** [comment]
Hi. 
Instead of using a callback, you can use : https://github.com/azlux/pymumble/blob/pymumble_py3/API.md#soundqueue-object-accessible-through-usersound
You can receive the sound with a loop, and you will know when there are no data.

**Comment by sp2ong** [comment]
OK, thanks for your answer and I'll try to use it.
