### ISSUE TITLE
Bot cannot send commands immediately after receiving serversync, and attempts will block further commands.

### ISSUE THREAD

**Issue by CaptainZidgel** [azlux/pymumble#86]
ServerSync is the message sent by Murmur when the Client is all caught up and has all the information it needs to proceed. This is marked in pymumble with `PYMUMBLE_CLBK_CONNECTED`. Using callbacks, one can see that on this event they indeed have all the channels and users stored in their Mumble object, but attempting to use any command (ex: `User.send_text_message` or `Channel.send_text_message`. I did not test any other commands but these and `Channel.get_acl()` which seemed conclusive enough to me.) will halt the entire command process (I don't know the correct terminology, nor if this is a wholly accurate descriptor). Consequences:
The callback will not proceed from the command invocation.
New callbacks can start.
Any other commands that attempt to be sent are not sent and again halt their callback.

Here's an example of what I mean:

```python
#"First Case" (broken)
def onReady():
    print("ready")
    c = bot.channels[1]
    c.send_text_message("HI")
    print("Post-ready")
    
def onmsg(event):
    print("Received")
    bot.channels[1].send_text_message("Pong")
    print("sent")

bot.callbacks.set_callback(PYMUMBLE_CLBK_CONNECTED, onReady)
bot.callbacks.set_callback(PYMUMBLE_CLBK_TEXTMESSAGERECEIVED, onmsg)
```
1) Bot: Send message to channel on ready. Not sent.
2) Test User (me): Send message to bot after it connects
3) Bot receives the callback, does not finish. No message is sent.
4) Test User: Sends another message as a test
5) Bot user again receives, does not finish. No message is sent.
The corresponding output:
```
ready
Received
Received
```
Now the same, without sending a command after connecting.
```python
#"Second Case" (working)
def onReady():
    print("ready")
    c = bot.channels[1]
    #c.send_text_message("HI")
    print("Post-ready")
    
def onmsg(event):
    print("Received")
    bot.channels[1].send_text_message("Pong")
    print("sent")

bot.callbacks.set_callback(PYMUMBLE_CLBK_CONNECTED, onReady)
bot.callbacks.set_callback(PYMUMBLE_CLBK_TEXTMESSAGERECEIVED, onmsg)
```
All messages are received.
Corresponding output:
```
ready
Post-ready
Received
sent
Received
sent
```

If you were to add a print statement to `message.TextMessage` (what `Channel.send_test_message()` calls), you would see it is always called, but if you add a print statement at the top of `Mumble.treat_command`, you'll find it is never called in the first case, but is sent during the second case.

(I have been able to recreate this issue on commits 9de35a5 and 5011492)

**Comment by azlux** [comment]
Hi.
How do you create the bot object ?
To send data, you need to wait it is ready with : `mumble.is_ready()`
With you callback on the very first configuration message, you try to send a value the bot isn't able to manage.
I'm not sure where the blocking occur. You don't have stderr ?

**Comment by CaptainZidgel** [comment]
To create my bot object:
`bot = pymumble.Mumble("(local bonjour server)", "(username)", certfile="bot.pem", keyfile="bot.key", debug=False)`
before the callbacks are written,
and afterwards:
```
bot.start()

while True:
    bot.loop()
```

I'll admit I didn't have it before you wrote, but now I have it. The code works if I move my `onReady` code to happen after `bot.is_ready()`, which in turn comes after `bot.start()` but that seems undesirable to me. Would it be unwise/unsafe to automatically wait with `mumble.is_ready()` before sending `PYMUMBLE_CLBK_CONNECTED`?

**Comment by azlux** [comment]
I think the best to do is to create a new callback `PYMUMBLE_CLBK_READY` for your case.
Can you start the bot in debug mode (`debug=True` in the Mumble class) ?
You will see every messages sond with the server this way.

**Comment by CaptainZidgel** [comment]
With debug=True, it confirms no message is being sent for First Case.

Second Case (querying ACL on message):
```
2020-10-06 14:45:45,713-PyMumble-DEBUG-1602020745713
2020-10-06 14:45:47,485-PyMumble-DEBUG-read control connection
2020-10-06 14:45:47,485-PyMumble-DEBUG-dispatch control message
2020-10-06 14:45:47,485-PyMumble-DEBUG-message: TextMessage : actor: 133
session: 132
message: "aaa" //this is the test message i sent to trigger

2020-10-06 14:45:47,486-PyMumble-DEBUG-sending message
2020-10-06 14:45:47,487-PyMumble-DEBUG-read control connection
2020-10-06 14:45:47,487-PyMumble-DEBUG-dispatch control message
2020-10-06 14:45:47,487-PyMumble-DEBUG-message: ACL : {My server's ACLs...}
```

First Case (querying during onready, this code was run with `bot.is_ready()` following `bot.start()`. It occasionally causes a segfault without `is_ready()`):
No such message follows the serversync message
```
2020-10-06 14:47:25,861-PyMumble-DEBUG-read control connection
2020-10-06 14:47:25,861-PyMumble-DEBUG-dispatch control message
2020-10-06 14:47:25,861-PyMumble-DEBUG-message: serversync : session: 134
max_bandwidth: 72000
permissions: 135202815

2020-10-06 14:47:25,862-PyMumble-DEBUG-Bandwidth is 72000, downgrading to 52400 due to the protocol overhead
```

Having users call `is_ready()` in each script isn't a bad solution per se but I have a natural aversion to boilerplate code like this. A ready callback seems fine to me.

**Comment by azlux** [comment]
I maybe have a fix.

See those two lines : https://github.com/azlux/pymumble/blob/9de35a56f177aa179caa9ae0152241369e9ce282/pymumble_py3/mumble.py#L331-L332
Can you try to flip the 2 lines ?

**Comment by CaptainZidgel** [comment]
The fix works perfectly!
For posterity:
debug=True:
```
2020-10-06 15:12:00,126-PyMumble-DEBUG-message: serversync : session: 137
max_bandwidth: 72000
permissions: 135202815

2020-10-06 15:12:00,132-PyMumble-DEBUG-Bandwidth is 72000, downgrading to 52400 due to the protocol overhead
ready //print statement
2020-10-06 15:12:00,132-PyMumble-DEBUG-sending message
2020-10-06 15:12:00,132-PyMumble-DEBUG-read control connection
2020-10-06 15:12:00,132-PyMumble-DEBUG-dispatch control message
2020-10-06 15:12:00,133-PyMumble-DEBUG-message: ACL : {server ACLs...}
```
It works with no need for `is_ready` call:
```python
bot = pymumble.Mumble("host", "bot", certfile="bot.pem", keyfile="bot.key", debug=True)

def onacl(event):
    print(event) 
 
def onReady():
    print("ready")
    bot.channels[0].get_acl()

bot.callbacks.set_callback(PYMUMBLE_CLBK_ACLRECEIVED, onacl)
bot.callbacks.set_callback(PYMUMBLE_CLBK_CONNECTED, onReady)

bot.start()
while True:
    bot.loop()
```

**Comment by azlux** [comment]
BTY : you don't need the loop into the infinite `while`. the `Mumble.loop()` is run by the init/start function.

```python3
while True:
    time.sleep(1)
```
is enought
