### ISSUE TITLE
User local volume adjustment

### ISSUE THREAD

**Issue by fcuringa** [azlux/pymumble#94]
Hi,

First of all I would like to thank you for you great work on this project.
There is a useful feature in the Mumble client I cannot find in `pymumble`, it is called "Local volume adjustment" and it allows a user to selectively adjust the incoming volume level from a specific other user. Here is a screenshot.

![image](https://user-images.githubusercontent.com/17481832/105333628-3aa5b780-5bd6-11eb-9d14-19e38fb4186f.png)

Is this available through some method or is it not implemented? 

Thanks!

**Comment by azlux** [comment]
Hi,
On pymumble, you can have the incoming sound separated by users. You can make this part on your own, not sure this kind of process need to be include inside a library.
This not exist at that moment. You can make a PR, Maybe the lib audioop.mul can do the work for you.
