### ISSUE TITLE
music quality using ffmpeg

### ISSUE THREAD

**Issue by pramadhana92** [azlux/pymumble#95]
Hi,

I'm trying to play music from my computer to mumble server.
I'm using example from #90 **added example for playing music via ffmpeg**

I'm using windows, and ffmpeg build from [gyan.dev](https://www.gyan.dev/ffmpeg/builds/)

this is sample of my code (exactly same from example)
```
    command = ["ffmpeg", "-i", file, "-acodec", "pcm_s16le", "-f", "s16le", "-ab", "192k", "-ac", "1", "-ar", "48000",  "-"]
    sound = sp.Popen(command, stdout=sp.PIPE, stderr=sp.DEVNULL, bufsize=1024)
    print("playing")
    while True:
        raw_music = sound.stdout.read(1024)
        if not raw_music:
            break
        #mumble.sound_output.add_sound(audioop.mul(raw_music, 2, vol))   #adjusting volume
        mumble.sound_output.add_sound(raw_music)
```

I'm playing .mp3 and .mp4 file, but the quality is bad.
if I change the parameter in command, the quality of the sound is getting wose

I found if I change this line
`raw_music = sound.stdout.read(1024)` to `raw_music = sound.stdout.read()`
the quality of the sound is better, but still there is some noise and missing sound

can someone help me to get better configuration?

Thanks for all of your help, I really appreciate it!

**Comment by DuckBoss** [comment]
Hello! I have an advanced mumble bot that uses FFmpeg for part of it's audio plugin.
Here is a snippet of the process that I use:

[Direct Link](https://github.com/DuckBoss/JJMumbleBot/blob/1eb6cd080aa162cc26f665648d6f67b834cb22d3/JJMumbleBot/lib/audio/audio_interface.py#L68-L79)

FFmpeg parameter setup:
``` 
    if audio_lib_type.value == AudioLibrary.FFMPEG.value:
        params = [audio_lib_path]
        if quiet:
            params.extend(["-loglevel", "quiet"])
        if use_reconnect:
            params.extend(["-reconnect", "1", "-reconnect_streamed", "1", "-reconnect_delay_max", "2"])
        params.extend(["-i", uri, "-ss", f"{skipto}", "-acodec", "pcm_s16le", "-f", "s16le",
                       "-ab", "192k", "-ac", "2"])
        if stereo:
            params.extend(["-ar", "48000", "-threads", "8", "-"])
        else:
            params.extend(["-ar", "24000", "-threads", "8", "-"])
```
Subprocess opening:
``` 
sp.Popen(params, stdout=sp.PIPE, bufsize=1024)
```
Reading audio data from stdout:
``` 
audio_inst.stdout.read(1024)
```
As you can see I use stereo output from FFmpeg, and since mumble (as of v1.3) doesn't support stereo audio, I also use a mumble 1.4 snapshot pre-release version that supports stereo audio which makes the quality about 90-95% close to the original.
Another important parameter I use is `-threads 8`  which allows the audio work to be spread out between 8 threads causing less interruptions and crackling sounds.

I hope this helps!

**Comment by pramadhana92** [comment]
Hi @DuckBoss ! Thanks for your reply!

You're right by adding parameter `-threads 8`  better quality. But, I still get some packet loss. Maybe because my internet connection not really good.

Thanks for your help!

**Comment by DuckBoss** [comment]
Have you tried creating a private mumble server on your local computer and running your script on the same machine?
You will be able to test the quality without worrying about your internet connection.

**Comment by pramadhana92** [comment]
Oh yeah that's a good idea to check whether it's internet problem or not.
Thanks for your suggestion!

**Comment by pramadhana92** [comment]
hi @DuckBoss and all. I found the cause of noise when playing music using pymumble.
It's not the fault of source code, but caused by bandwidth setting in murmur.ini

You will hear noise if you set bandwidth below 32000. And will not hear noise if you put bandwidth above 48000. Maybe it depends on the sound bitrate. But, the point is we must configure correct bandwidth in murmur.ini

In the end, the code from example is working fine!
[LINK](https://github.com/azlux/pymumble/blob/b32a94ef2e66552129721da97c60fb64a37e37fd/examples/music_bot.py#L29)
