### ISSUE TITLE
Kick/Ban features not working

### ISSUE THREAD

**Issue by DuckBoss** [azlux/pymumble#96]
Hello,

I'm working on implementing kick/ban features into [JJMumbleBot](https://github.com/DuckBoss/JJMumbleBot), and
I'm running into an issue where the kick/ban methods don't seem to be doing anything.
For some context:
 - The bot client is connected to the server with a cert file.
 - The server has given full permissions to the bot client.
 - My debug print statements are able to identify that an actual user is trying to be kicked (by verifying the name/session)

My `!kickuser 'name'` command loops through all the users in the server, finds the user with the matching name and attempts to kick them using the user object like so: `mumble.users[my_user].kick(reason="test")`
I'm not receiving any errors from pymumble, and the server doesn't have any messages regarding the attempted kick.
I also tried subscribing to the permission_denied callback, but I didn't receive any permission errors.

Do you have any ideas as to why the kick/ban methods aren't working?

**Comment by azlux** [comment]
Hi,
Please check your code, I don't see any issue on Pymumble.
```
[22:28:02] TestBot s'est connecté et a rejoint le salon
[22:28:04] Vous avez été expulsé du serveur par TestBot : Kick_reason.
```

I've been kick with the code : 

```python3
import time
import pymumble_py3

server = "mumble.azlux.fr"
nick = "TestBot"
passwd = ""

mumble = pymumble_py3.Mumble(server, nick, password=passwd, certfile="test.pem", keyfile="test.pem.key")
mumble.start()

time.sleep(2)
print(mumble.users[24].kick(reason="Kick_reason"))

while True:
    time.sleep(1)
```

**Comment by DuckBoss** [comment]
Hi, I can't seem to narrow down the issue. Do you think I need a keyfile in addition to the certfile I use to connect to the server? Or is that not related?

**Comment by azlux** [comment]
If your `.pem` don't have the key include, you will have a `ssl.SSLError: [SSL] PEM lib` error if you don't mention a separate file  (.pem allow having multiple information in the same file).
If you're connected with admin access, it's not a SSL issue.
Did you try to run pymumble in debug mode ?

**Comment by DuckBoss** [comment]
I'll try your suggestion and let you know how it goes. Thanks!

**Comment by DuckBoss** [comment]
I fixed the issue. It ended up being an issue with the server ACLs.
