### ISSUE TITLE
Moving users across channels?

### ISSUE THREAD

**Issue by DuckBoss** [azlux/pymumble#97]
Hello,

I noticed the recent work on ACL management and channels 
and I was wondering if there was any feature to move users from one channel to another.

Thanks

**Comment by azlux** [comment]
Please check https://github.com/azlux/pymumble/blob/pymumble_py3/API.md#channel-object-accessible-through-mumblechannelschannel_id-or-mumblechannelsfind_by_namename

`Channel.move_in(session=None)` can help you

**Comment by DuckBoss** [comment]
Wow that's interesting, I always thought that the move_in(...) function was only capable of moving the library client.
Thanks for the update!
